name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pip install coveralls
        pip install .

    - name: Start server
      run: |
        source venv/bin/activate
        python3 -c "from pyweber.utils.router import Router, Template; from pyweber.utils.server import Server; router = Router(); router.add_route('/', Template('<html><head><title Pytest Greetings/></head><body>Pytest greetings: hello world</body></html>')); server = Server(router); server.run()" &
        sleep 5  # Dê tempo suficiente para o servidor iniciar

    - name: Wait for server to be ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5555/; then
            echo "✅ Servidor iniciado com sucesso!"
            exit 0
          fi
          echo "⌛ Aguardando servidor iniciar ($i/10)..."
          sleep 1
        done
        echo "❌ O servidor não iniciou corretamente!"
        exit 1
    
    - name: Run tests and send coverage to Coveralls
      run: |
        source venv/bin/activate
        pytest --cov=pyweber.utils --cov-report=term-missing
        coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests --maxfail=1 --disable-warnings -q
