name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install .

    - name: Start server
      run: |
        source venv/bin/activate
        python3 -c "from pyweber.utils.server import Server; Server(None).run()" &  # Inicia em background
        sleep 2  # Pequena espera antes de checar o status

    - name: Wait for server to be ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5555/; then
            echo "✅ Servidor iniciado com sucesso!"
            exit 0
          fi
          echo "⌛ Aguardando servidor iniciar ($i/10)..."
          sleep 1
        done
        echo "❌ O servidor não iniciou corretamente!"
        exit 1

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests --maxfail=1 --disable-warnings -q
