name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install .  

    - name: Start server
      run: |
        source venv/bin/activate
        nohup python3 -c "from pyweber.utils.server import Server; Server(None).run()" > server.log 2>&1 &
        sleep 5  # Espera o servidor iniciar

    - name: Check if server is running
      run: |
        if ! curl -s http://localhost:5555/; then
          echo "❌ O servidor não iniciou corretamente!"
          exit 1
        fi

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests --maxfail=1 --disable-warnings -q