name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Certifique-se de que está usando a versão correta do Python

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências do projeto
        pip install .  # Instala o pacote pyweber localmente

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests --maxfail=1 --disable-warnings -q  # Executa os testes
